spring:
  profiles: test
  thymeleaf:
    # 调试环境下使用false，生产环境要设为true，否则会影响性能
    cache: true
jdbc:
  master:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://172.19.70.3:5447/yzgdb
    username: postgres
    password: P@s5w0rd
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWait: 5000
    timeBetweenEvictionRunsMillis: 9000
    minEvictableIdleTimeMillis: 300000
    maxPoolPreparedStatementPerConnectionSize: 20