spring:
  config:
    active:
      on-profile: test
uranus:
  datasource:
    master:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://172.19.70.3:5447/yzgdb
      username: postgres
      password: P@s5w0rd
      minimum-idle: 1
      maximum-pool-size: 10
      connection-timeout: 15000
      pool-name: master