spring:
  config:
    active:
      on-profile: dev
uranus:
  datasource:
    master:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: soon0116
      minimum-idle: 1
      maximum-pool-size: 10
      connection-timeout: 15000
      pool-name: master
